version: '3.9'

services:
  portfolio-app:
    image: registry.helixx.cloud/portfolio-deployment:latest
    container_name: portfolio-app
    ports:
      - "8989:8989"
    environment:
      - PORT=8989
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./content:/app/content  # Mount content directory for easy updates
      - ./static:/app/static    # Mount static files for updates
      - ./templates:/app/templates # Mount templates for updates
    restart: unless-stopped
