apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deployment
  labels:
    app: portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: portfolio
        image: registry.helixx.cloud/portfolio-deployment:latest
        ports:
        - containerPort: 8181
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: true
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
        volumeMounts:
        - name: proc
          mountPath: /host/proc
          readOnly: true
      securityContext:
        fsGroup: 1000
      volumes:
      - name: proc
        hostPath:
          path: /proc
      imagePullSecrets:
      - name: regcred # Reference to the private registry secret