apiVersion: v1
kind: Service
metadata:
  name: portfolio-deployment
spec:
  ports:
    - port: 8181
      protocol: TCP
      targetPort: 8181
  selector:
    app: portfolio-deployment
  type: LoadBalancer
